package cardscollection;



import java.awt.Color;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aristah
 * @atsewaj@gmail.com
 * @tech-it 
 */
public class PickCardsGUI extends javax.swing.JFrame {
    
    

    static String username ="";    
    URL url1;
    String sellected_file_url ="playersFile/players1.txt";
    String choosertitle;
    JFileChooser chooser;
     
    static int no_simulations_count=0;
    static ArrayList<String> picks_outcome= new ArrayList<>();

    /**
     * Creates new form Main
     */
    public PickCardsGUI() {
        initComponents();
             printjButton.setEnabled(false);
             savejButton.setEnabled(false);
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Images/icon.jpg"));
         initjcombobox(sellected_file_url);
        username=display_player_name_jComboBox.getName();
       
        
        //border color of panel
        Color border = new Color(50, 20, 20, 55);
       jPanel1.setBorder(BorderFactory.createLineBorder(border, 10));

    }
    

     //Accepting file as input to jcombobox
    public void initjcombobox(String file_name_path)
    {
        this.sellected_file_url=file_name_path;
        DefaultComboBoxModel model =new DefaultComboBoxModel();
         url1 = getClass().getResource(sellected_file_url);
        
         String splitUrl = url1.toString();
         System.out.println(splitUrl.substring(6));
        String fileName =splitUrl.substring(6);
        System.out.println(fileName);
      
        File file = new File(fileName);
        
        try(Scanner in = new Scanner(file))
        {
            while(in.hasNextLine())
            {
                String line;
                line = in.nextLine();
                model.addElement(line);
                display_player_name_jComboBox.setModel(model);
            }
            
  
        }catch(FileNotFoundException ex)
        {
            System.out.println("File not found");
        }
    }
    
    
    //Metthod for choosing a file to read player details
    
    public String readNewPlayerFile()
    {
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(choosertitle);
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
          
        chooser.setFileFilter(filter);
        
        
        chooser.setAcceptAllFileFilterUsed(false);
        
        if(chooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            System.out.println("getCurrentDirectory() :"+ chooser.getCurrentDirectory());
            
             System.out.println("getSelectedFile() :"+ chooser.getSelectedFile());
        }else{
             System.out.println("No Selection");
        }
        
        return chooser.getSelectedFile().toString();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        card_first_jLabel = new javax.swing.JLabel();
        card_third_jLabel = new javax.swing.JLabel();
        card_second_jLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numberOfPicksjLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numberOfSimulationsjLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        display_player_name_jComboBox = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();
        printjButton = new javax.swing.JButton();
        gojButton = new javax.swing.JButton();
        quitjButton = new javax.swing.JButton();
        card_fourth_jLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cards Collection");
        setBackground(new java.awt.Color(255, 204, 102));
        setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        setResizable(false);

        card_first_jLabel.setBackground(new java.awt.Color(255, 51, 204));
        card_first_jLabel.setForeground(new java.awt.Color(51, 255, 153));
        card_first_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card_first_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.jpg"))); // NOI18N
        card_first_jLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        card_third_jLabel.setBackground(new java.awt.Color(102, 255, 255));
        card_third_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card_third_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.jpg"))); // NOI18N
        card_third_jLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        card_second_jLabel.setBackground(new java.awt.Color(102, 255, 255));
        card_second_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card_second_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.jpg"))); // NOI18N
        card_second_jLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Number of picks  :");

        numberOfPicksjLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numberOfPicksjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOfPicksjLabel.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Number of Simulations :");

        numberOfSimulationsjLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numberOfSimulationsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOfSimulationsjLabel.setText("0");

        jLabel9.setText("Player :");

        display_player_name_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_player_name_jComboBoxActionPerformed(evt);
            }
        });

        jButton6.setText("Delete Player");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Add Player");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        printjButton.setText("Print");
        printjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printjButtonActionPerformed(evt);
            }
        });

        gojButton.setText("Go");
        gojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gojButtonActionPerformed(evt);
            }
        });

        quitjButton.setText("Quit");
        quitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitjButtonActionPerformed(evt);
            }
        });

        card_fourth_jLabel.setBackground(new java.awt.Color(102, 255, 255));
        card_fourth_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card_fourth_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.jpg"))); // NOI18N
        card_fourth_jLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(gojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(card_second_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(card_first_jLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(display_player_name_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(savejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quitjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numberOfSimulationsjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberOfPicksjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(card_third_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(card_fourth_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(card_third_jLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(card_second_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card_first_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(card_fourth_jLabel))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfPicksjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfSimulationsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(display_player_name_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 102));

        jMenu1.setText("File");

        jMenuItem3.setText("clear");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("print ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("save");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Action");

        jMenuItem7.setText("statistics");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenu4.setText("Options");

        jMenuItem8.setText("Replacement");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("No Replacement");
        jMenu4.add(jMenuItem9);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        numberOfPicksjLabel.setText("0");
        numberOfSimulationsjLabel.setText("0");
            no_simulations_count=0;
              picks_outcome.clear();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void gojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gojButtonActionPerformed
         //DeckOfCards d = new DeckOfCards();
     //String[] args
     
     printjButton.setEnabled(true);
     savejButton.setEnabled(true);
     display_player_name_jComboBox.setEnabled(true);
     DeckOfCards.main();
         ArrayList<String> number_picked = DeckOfCards.number_picked;
          ArrayList<String> suite_picked = DeckOfCards.suite_picked;
         
         int no_of_picks = DeckOfCards.count;
         
         no_simulations_count ++;
                 
       
         //String no_of_picks_to_string = (no_of_picks);
         numberOfPicksjLabel.setText(String.valueOf(no_of_picks));
         numberOfSimulationsjLabel.setText(String.valueOf( no_simulations_count));
         
        
         System.out.println("User Number of picks"+no_of_picks);
         
         String first_no =number_picked.get(0);
         String first_suite =suite_picked.get(0);
         
         
         String second_no =number_picked.get(1);
         String second_suite =suite_picked.get(1);
         
         String third_no =number_picked.get(2);
         String third_suite =suite_picked.get(2);
         
         String fourth_no =number_picked.get(3);
         String fourth_suite =suite_picked.get(3);
         
         System.out.println("No picked : " +first_no +"Suite" +suite_picked.get(0));
         System.out.println("No picked : " +number_picked.get(1) +"Suite" +suite_picked.get(1));
         System.out.println("No picked : " +number_picked.get(2) +"Suite" +suite_picked.get(2));
         System.out.println("No picked : " +number_picked.get(3) +"Suite" +suite_picked.get(3));

         
         /*Fist Card
          Ace selected
         */
         if(first_no=="Ace")
         {
             if(first_suite=="Clubs"){
                String image_path = "images/clubs_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }else{
                
            }
         }
         
          /*Fist Card
          A Two selected
         */
         else if(first_no=="2"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
          /*Fist Card
          A Three selected
         */
         else if(first_no=="3"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
          /*Fist Card
          A Four selected
         */
         else if(first_no=="4"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }else{
                
            }        
         }
         
         
         
          /*Fist Card
          A Three selected
         */
         else if(first_no=="5"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
         
           /*Fist Card
          A six selected
         */
         else if(first_no=="6"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
         
           /*Fist Card
          A seven selected
         */
         else if(first_no=="7"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
                  
           /*Fist Card
          A Eight selected
         */
         else if(first_no=="8"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
         
           /*Fist Card
          A nine selected
         */
         else if(first_no=="9"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
           /*Fist Card
          A ten selected
         */
         else if(first_no=="10"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
          /*Fist Card
          A Jack selected
         */
         else if(first_no=="Jack"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
          /*Fist Card
          A King selected
         */
         else if(first_no=="King"){
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Diamonds"){
                String image_path = "images/diamonds_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
           /*Fist Card
          Queen selected
         */
        else {
              if(first_suite=="Clubs"){
                String image_path = "images/clubs_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
             else if(first_suite=="Spades"){
                String image_path = "images/spades_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else if(first_suite=="Hearts"){
                String image_path = "images/hearts_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }
            else{
                String image_path = "images/diamonds_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_first_jLabel.setIcon(image);
             }        
         
         }
              
         //############################ Second bit  
              
              
         /*Second Card
          Ace selected
         */
         if(second_no=="Ace")
         {
             if(second_suite=="Clubs"){
                String image_path = "images/clubs_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else{
                
            }
         }
         
          /*Second Card
          A Two selected
         */
         else if(second_no=="2"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
          /*Second Card
          A Three selected
         */
         else if(second_no=="3"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
          /*Second Card
          A Four selected
         */
         else if(second_no=="4"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_second_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
         
          /*Second Card
          A five selected
         */
         else if(second_no=="5"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
         
           /*second Card
          A six selected
         */
         else if(second_no=="6"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
         
           /*second Card
          A seven selected
         */
         else if(second_no=="7"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }else{
                
            }        
         }
         
                  
           /*second Card
          A Eight selected
         */
         else if(second_no=="8"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
         
           /*Second Card
          A nine selected
         */
         else if(second_no=="9"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
           /*Fist Card
          A ten selected
         */
         else if(second_no=="10"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }else{
                
            }        
         }
         
         
          /*second Card
          A Jack selected
         */
         else if(second_no=="Jack"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }  else{
                
            }
         }
         
         
          /*second Card
          A King selected
         */
         else if(second_no=="King"){
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
           /*Second Card
          Queen selected
         */
        else {
              if(second_suite=="Clubs"){
                String image_path = "images/clubs_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
             else if(second_suite=="Spades"){
                String image_path = "images/spades_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Hearts"){
                String image_path = "images/hearts_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }
            else if(second_suite=="Diamonds"){
                String image_path = "images/diamonds_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_second_jLabel.setIcon(image);
             }  else{
                
            }      
         }     
              
              
              
           
         
         
          //############################ Third bit  
              
              
         /*Third Card
          Ace selected
         */
         if(third_no=="Ace")
         {
             if(third_suite=="Clubs"){
                String image_path = "images/clubs_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }else{
                
            }
         }
         
          /*Third Card
          A Two selected
         */
         else if(third_no=="2"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
          /*Third Card
          A Three selected
         */
         else if(third_no=="3"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_third_jLabel.setIcon(image);
             }else{
                
            }        
         }
         
          /*Third Card
          A Four selected
         */
         else if(third_no=="4"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_third_jLabel.setIcon(image);
             }        
         }
         
         
         
          /*Third Card
          A Three selected
         */
         else if(third_no=="5"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
         
           /*Third Card
          A six selected
         */
         else if(third_no=="6"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
         
           /*Third Card
          A seven selected
         */
         else if(third_no=="7"){
              if(third_suite.equals("Clubs")){
                String image_path = "images/clubs_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }else{
                
            }        
         }
         
                  
           /*Third Card
          A Eight selected
         */
         else if(third_no=="8"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
         
           /*Third Card
          A nine selected
         */
         else if(third_no=="9"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
           /*Third Card
          A ten selected
         */
         else if(third_no=="10"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             } else{
             
         }       
         }
         
         
          /*Third Card
          A Jack selected
         */
         else if(third_no=="Jack"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_third_jLabel.setIcon(image);
             }else{
                
            }        
         }
         
         
          /*Third Card
          A King selected
         */
         else if(third_no=="King"){
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
           /*Second Card
          Queen selected
         */
        else {
              if(third_suite=="Clubs"){
                String image_path = "images/clubs_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
             else if(third_suite=="Spades"){
                String image_path = "images/spades_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Hearts"){
                String image_path = "images/hearts_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             }
            else if(third_suite=="Diamonds"){
                String image_path = "images/diamonds_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_third_jLabel.setIcon(image);
             } else{
                
            }       
         } 
         
         
                   //############################ Fourth bit  
              
              
         /*Fourth Card
          Ace selected
         */
         if(fourth_no=="Ace")
         {
             if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_ace.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else{
                
            }
         }
         
          /*Fourth Card
          A Two selected
         */
         else if(fourth_no=="2"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_two.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             } 
            else{
                
            }
         }
         
          /*Fourth Card
          A Three selected
         */
         else if(fourth_no=="3"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_three.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_fourth_jLabel.setIcon(image);
             } 
              
            else{
                
            }
         }
         
          /*Fourth Card
          A Four selected
         */
         else if(fourth_no=="4"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_four.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
              card_fourth_jLabel.setIcon(image);
             }  
            else{
                
            }
         }
         
         
         
          /*Fourth Card
          A Three selected
         */
         else if(fourth_no=="5"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_five.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }   else{
                
            }     
         }
         
         
         
           /*Fourth Card
          A six selected
         */
         else if(fourth_no=="6"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_six.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
         
           /*Fourth Card
          A seven selected
         */
         else if(fourth_no=="7"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_seven.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
                  
           /*Fourth Card
          A Eight selected
         */
         else if(fourth_no=="8"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_eight.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
         
           /*Fourth Card
          A nine selected
         */
         else if(fourth_no=="9"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_nine.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }else{
                
            }        
         }
         
           /*Fourth Card
          A ten selected
         */
         else if(fourth_no=="10"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_ten.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             } else{
                
            }       
         }
         
         
          /*Fourth Card
          A Jack selected
         */
         else if(fourth_no=="Jack"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_jack.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
               card_fourth_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
         
          /*Fourth Card
          A King selected
         */
         else if(fourth_no=="King"){
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_king.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }  else{
                
            }      
         }
         
           /*Fourth Card
          Queen selected
         */
        else {
              if(fourth_suite=="Clubs"){
                String image_path = "images/clubs_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
             else if(fourth_suite=="Spades"){
                String image_path = "images/spades_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Hearts"){
                String image_path = "images/hearts_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }
            else if(fourth_suite=="Diamonds"){
                String image_path = "images/diamonds_queen.png";  
                ImageIcon image = new ImageIcon(getClass().getClassLoader().getResource(image_path));
                card_fourth_jLabel.setIcon(image);
             }   else{
                
            }     
         }   
            
         picks_outcome.add(String.valueOf(no_of_picks));
         number_picked.clear();
         suite_picked.clear();

    }//GEN-LAST:event_gojButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
         String urlFileSelected =readNewPlayerFile();
         
         String[] assetClass = urlFileSelected.split("\\\\");
         System.out.println("The file path is...."+urlFileSelected );
         System.out.println( assetClass[assetClass.length-1]);
         
         String filName =assetClass[assetClass.length-1];
         sellected_file_url ="playersFile/"+filName;
         
         initjcombobox(sellected_file_url);
         
         String username =display_player_name_jComboBox.getSelectedItem().toString();
         
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         new Statistics().setVisible(rootPaneCheckingEnabled);
         this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void quitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitjButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitjButtonActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void display_player_name_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_player_name_jComboBoxActionPerformed
        // TODO add your handling code here:
               
    }//GEN-LAST:event_display_player_name_jComboBoxActionPerformed

    private void printjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printjButtonActionPerformed
        // TODO add your handling code here:
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printjButtonActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Statistics stats = new Statistics();
        PrintUtilities.printComponent( stats);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
         String username =display_player_name_jComboBox.getSelectedItem().toString();
        try {
            // TODO add your handling code here:
            
            File file = new File("user.txt");   //creating file object
            FileWriter fw;
            
            fw = new FileWriter(file); //create fileWriter object
            PrintWriter pw = new PrintWriter(fw);
            pw.println("Player's Username :");
            pw.println("Player's Account Balance :");
            pw.close();
        } catch (IOException ex) {
            Logger.getLogger(PickCardsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_savejButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        display_player_name_jComboBox.setEnabled(false);
             printjButton.setEnabled(false);
             savejButton.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    
    public void firstCard(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Splash mySplash = new Splash(4000);
        mySplash.showSplash();
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PickCardsGUI().setVisible(true);
            }
        });
        
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel card_first_jLabel;
    private javax.swing.JLabel card_fourth_jLabel;
    private javax.swing.JLabel card_second_jLabel;
    private javax.swing.JLabel card_third_jLabel;
    private javax.swing.JComboBox<String> display_player_name_jComboBox;
    private javax.swing.JButton gojButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numberOfPicksjLabel;
    private javax.swing.JLabel numberOfSimulationsjLabel;
    private javax.swing.JButton printjButton;
    private javax.swing.JButton quitjButton;
    private javax.swing.JButton savejButton;
    // End of variables declaration//GEN-END:variables
}
